version: '3'
services:
  web:
    build: ./ngular-app
    ports:
      - "80:80"
    links:
      - node
    volumes:
      - ./ngular-app/dist:/usr/share/nginx/html
  node:
    build: ./node-app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"